spring.application.name=SistemaVenda

# ==================================================
# JPA / HIBERNATE
# ==================================================

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# ==================================================
# JACKSON
# ==================================================

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# ==================================================
# UPLOADS
# ==================================================

app.upload.directory=/var/lib/sistema-venda/upload

spring.web.resources.static-locations=file:/var/lib/sistema-venda/upload/

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# ==================================================
# DATABASE
# ==================================================

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_venda
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================================================
# HIKARI
# ==================================================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ==================================================
# SPRING
# ==================================================

spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.mandatory-file-encoding=UTF-8

# ==================================================
# LOGGING
# ==================================================

logging.config=classpath:logback.xml

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.jdbc.core=INFO

# ==================================================
# ACTUATOR
# ==================================================

management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/actuator

# ==================================================
# CACHE
# ==================================================

spring.cache.type=simple

# ==================================================
# EMAIL
# ==================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true