spring.application.name=SistemaVenda

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.web.resources.static-locations=file:upload/
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_venda
spring.datasource.username=root
#spring.datasource.password=kdanjoskd
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

logging.config=classpath:logback.xml
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=debug

spring.mandatory-file-encoding=UTF-8
logging.level.org.springframework.jdbc.core=DEBUG
# Expor todos os endpoints do Actuator
management.endpoints.web.exposure.include=*

# Habilitar detalhes dos endpoints (opcional)
management.endpoints.web.base-path=/actuator
spring.cache.type=simple



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=clinicasaudelivre@gmail.com
spring.mail.password=isyatiquznkrtlrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true